behaviors:
  TestModel:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 4096
      learning_rate: 0.00003
      beta: 0.03
      epsilon: 0.2
      epsilon_schedule: linear   
      lambd: 0.95
      num_epoch: 4
      learning_rate_schedule: linear
      beta_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 4
      vis_encode_type: simple
      use_recurrent: false
      sequence_length: 16 
    reward_signals:
      extrinsic:
        gamma: 0.9
        strength: 1.0
    max_steps: 5000000  # 5.000.000 times Envs (16)
    time_horizon: 2024
    summary_freq: 100000  # 10.000 times Envs (16)
    threaded: true
